import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { PetraWallet } from "petra-plugin-wallet-adapter";
import { AptosWalletAdapterProvider } from "@aptos-labs/wallet-adapter-react";
import { Network } from "@aptos-labs/ts-sdk";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "./_components/navbar";
import { Toaster } from "~/components/ui/sonner";
import { LoginModal } from "./_components/login-modal";
import { auth } from "~/auth";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  return (
    <AptosWalletAdapterProvider
      optInWallets={['Petra']}
      autoConnect={true}
      dappConfig={{ network: Network.DEVNET }}
    >
      <html lang="en" className={`${GeistSans.variable}`}>
        <body>
          <TRPCReactProvider><LoginModal />
          <Navbar />
          {children}
          <Toaster /></TRPCReactProvider>
        </body>
      </html>
    </AptosWalletAdapterProvider>
  );
}
